name: CI

on: 
  push:
  fork:

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: "uv"
        cache-dependency-glob: "requirements.txt"

    - name: setup python
      id: setup_python
      run: |
        uv python install 3.10.12
        uv venv my_env
        source my_env/bin/activate
        uv pip install -r requirements.txt

    - name: list packages
      id: list_pakcages
      run: |
        source my_env/bin/activate
        uv pip list
  
    - name: check links
      id: links
      run: |
        source my_env/bin/activate
        python -m pytest ./tests/test_check_links_in_ipynb.py ./utils/tests/

  badges:
    name: Add Google Colab Badges
    needs: test_links_utils
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: "uv"
        cache-dependency-glob: "requirements.txt"

    - name: setup python
      id: setup_python
      run: |
        uv python install 3.10.12
        uv venv my_env
        source my_env/bin/activate
        uv pip install -r requirements.txt

    - name: list packages
      id: list_pakcages
      run: |
        source my_env/bin/activate
        uv pip list

    - name: Add/Update badges
      id: badges
      run: |
        source my_env/bin/activate
        python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s

  test_ipynb:
    needs: badges
    name: test ipynb on Google Colab
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: "uv"
        cache-dependency-glob: "requirements.txt"

    - name: setup python
      id: setup_python
      run: |
        uv python install 3.10.12
        uv venv my_env
        source my_env/bin/activate
        uv pip install -r requirements.txt

    - name: list packages
      id: list_pakcages
      run: |
        source my_env/bin/activate
        uv pip list

    - name: pytest
      id: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run:  |
        source my_env/bin/activate
        python -m pytest -n auto -k 'not (links or update_nmisp_py)' ./tests
